<?php

// absolute filesystem path to this web root
define('WWW_DIR', dirname(__FILE__).'/..');

// absolute filesystem path to the application root
define('APP_DIR', WWW_DIR . '/app');

// absolute filesystem path to the libraries
define('LIBS_DIR', WWW_DIR . '/libs');

// Load Nette Framework or autoloader generated by Composer
require LIBS_DIR . '/autoload.php';


// Configure application
$configurator = new Nette\Config\Configurator;

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(APP_DIR . '/temp');
$configurator->createRobotLoader()
	->addDirectory(APP_DIR)
	->addDirectory(LIBS_DIR)
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(APP_DIR . '/config.neon');
if(file_exists(APP_DIR . '/config-server.neon'))
	$configurator->addConfig(APP_DIR . '/config-server.neon');
$container = $configurator->createContainer();


//do tricks:
$img = basename($container->httpRequest->url->path);
preg_match('~^(\d+)-(\d+)~', $img, $m);

if (file_exists("img/$m[0].png")) {
	$hash = \Casopisy\Obsah::getFilesSecretHash($m[1], $m[2], "");
	rename("img/$m[0].png", "img/$m[0]-$hash.png");

	header("Location: $_SERVER[REQUEST_URI]");
	exit;
}
else echo "error file not found";



